name: Anilist
on:
  # Schedule daily updates
  schedule: [{cron: "0 2,4,6,8,10,12,15,20 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.ani.svg
          token: ${{ secrets.METRICS_TOKEN }}
          plugin_anilist: yes
          plugin_anilist_user: hoogstaddie
          plugin_anilist_medias: anime
          plugin_anilist_sections: favorites, watching
          plugin_anilist_limit: 10
