name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "10 * * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.sem.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, repositories
          plugin_lines: yes
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_anilist: yes
          plugin_anilist_user: hoogstaddie
          plugin_anilist_medias: anime
          plugin_anilist_sections: favorites, completed
          plugin_anilist_limit: 10
